import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import MuiProvider from './_components/MuiProvider';
import { ReactNode } from 'react';

const font = Noto_Sans_JP({ weight: 'variable', preload: false });

export const metadata: Metadata = {
  title: 'SAFA',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang='ja'>
      <body className={font.className}>
        <MuiProvider>{children}</MuiProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
